### ISSUE TITLE
Issue, when using Client, makes Player and switches W and S key

### ISSUE THREAD

**Issue by ModxVoldHunter** [ArsenicClient/Arsenic#13]
1. Client switches Player movement and on Keys W and S

2. When in a game the module makes the play looking down with number 1 (text above)

ive config forge to stop Arsenic from crashing with Cloud Client (PVP Mod) & Optifine

============================================================

Minecraft Logs paste.ee link to view

https://paste.ee/p/OXKru

**Comment by PianoPenguin471** [comment]
Are you sure you didn't leave scaffold on?

**Comment by ModxVoldHunter** [comment]
> Are you sure you didn't leave scaffold on?

Nope I didn't even turn it on

**Comment by Cosmic-SC** [comment]
> 1. Client switches Player movement and on Keys W and S
> 2. When in a game the module makes the play looking down with number 1 (text above)
> 
> ive config forge to stop Arsenic from crashing with Cloud Client (PVP Mod) & Optifine
> 
> ============================================================
> 
> Minecraft Logs paste.ee link to view
> 
> https://paste.ee/p/OXKru

u probably broke something in the src pretty sure you've modified stuff

**Comment by K-ov** [comment]
Definitely got one of the scaffold modules enabled

**Comment by ModxVoldHunter** [comment]
> > 1. Client switches Player movement and on Keys W and S
> > 2. When in a game the module makes the play looking down with number 1 (text above)
> > 
> > ive config forge to stop Arsenic from crashing with Cloud Client (PVP Mod) & Optifine
> > ============================================================
> > Minecraft Logs paste.ee link to view
> > https://paste.ee/p/OXKru
> 
> u probably broke something in the src pretty sure you've modified stuff

i didn't modify anything in the mod, i just bulit it and put it mods folder, then all i did was modify forge loader settings ingame to prevent the PVP Client and the Hacked Client together. ill go and do a recheck if its not on ill take a screenshot and send it to here,

**Comment by Cosmic-SC** [comment]
> Definitely got one of the scaffold modules enabled

@ModxVoldHunter ^ check what kv said cuz it is impossible to switch keys without having scaffold enabled

**Comment by ModxVoldHunter** [comment]
> > Definitely got one of the scaffold modules enabled
> 
> @ModxVoldHunter ^ check what kv said cuz it is impossible to switch keys without having scaffold enabled

Solved, i think i did turn that on. closing
